# This workflow demonstrates how you can use various commands to get some helpful insight on the ubuntu container.

name: Details on ubuntu-lates

# Define when the workflow should run. On a push to main, a PR to main or manually with worfkow_dispatch
on: 
  push:
    branches: [ main ] 
  
  workflow_dispatch:

# Defining a single job to run

jobs:
  # Any job to run is defined here
  
  GetInfo:
    
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@v3   
    - run: |
       echo Who am I currently logged in as
       whoami
       echo       
       echo Showing the content of this directory on ubuntu machine
       ls -a
       echo # gaining an extra line
       echo Do we have Java on this machine
       java -version
       echo  
       echo Does it have Git installed?
       git --version
       echo
       echo Checking if some build tool exist
       echo
       echo Does it have mvn
       mvn --version
       echo
       echo Does it have Gradle
       gradle --version
       echo
       echo Does it have ant
       ant -version
       echo
       echo Does it have Android SDK - if so where?
       echo $ANDROID_SDK_ROOT
       echo
       echo Show the current workspace
       echo RUNNER_WORKSPACE       
       echo
       echo Show directory structure
       df       
      
    # Listing the detail is succefully completed
